#!/usr/bin/env node
import assert from 'node:assert/strict'
import crypto from 'node:crypto'
import { spawnSync } from 'node:child_process'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'

const root = path.resolve(process.argv[2] || '.')
const temp = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'alambic-nightly-')))
const vault = path.join(temp, 'vault')
const remote = path.join(temp, 'remote.git')
const home = path.join(temp, 'home')
const state = path.join(temp, 'state')
const gitconfig = path.join(temp, 'gitconfig')
const fake = path.join(temp, 'fake-distiller.sh')
const env = { ...process.env, HOME: home, ALAMBIC_ROOT: vault, ALAMBIC_STATE_DIR: state, GIT_CONFIG_GLOBAL: gitconfig, GIT_CONFIG_NOSYSTEM: '1', ALAMBIC_HARVEST_DISTILLER: fake }
for (const key of ['TYPESAFE_API_KEY', 'CLAUDE_CONFIG_DIR', 'CODEX_HOME', 'PI_CODING_AGENT_DIR', 'XDG_STATE_HOME']) delete env[key]
Object.assign(process.env, env)
for (const key of ['TYPESAFE_API_KEY', 'CLAUDE_CONFIG_DIR', 'CODEX_HOME', 'PI_CODING_AGENT_DIR', 'XDG_STATE_HOME']) delete process.env[key]
const cliPath = path.join(root, '_meta/alambic.mjs')
const cli = (argv) => spawnSync(process.execPath, [cliPath, ...argv], { cwd: vault, encoding: 'utf8', env, timeout: 300_000 })
const git = (argv, cwd = vault) => {
  const result = spawnSync('git', argv, { cwd, encoding: 'utf8', env })
  assert.equal(result.status, 0, `git ${argv.join(' ')}: ${result.stderr}`)
  return result.stdout.trim()
}
const nightly = (argv = ['--push']) => {
  const result = cli(['nightly', ...argv, '--json'])
  try { return { status: result.status, ...JSON.parse(result.stdout) } } catch { assert.fail(`nightly output is not JSON: ${result.stdout}${result.stderr}`) }
}
const remoteCount = () => Number(git(['rev-list', '--count', 'main'], remote))
const rich = 'We decided the lexical cache keeps raw fields because the root cause was _meta/lib/vault.mjs:42 and _meta/alambic.mjs:10. The fix passes and validated green. Decision: convention is lowercase tags. Also _meta/lib/harvest.mjs:5 confirms it.'
const writeSession = (name, id) => {
  const dir = path.join(home, '.claude/projects/-work-repo')
  fs.mkdirSync(dir, { recursive: true })
  const file = path.join(dir, name)
  fs.writeFileSync(file, [
    { type: 'user', sessionId: id, cwd: '/work/repo', message: { role: 'user', content: 'Why does the lexical cache break? fix it please' } },
    { type: 'assistant', sessionId: id, message: { role: 'assistant', content: [{ type: 'text', text: rich }] } },
    { type: 'user', sessionId: id, message: { role: 'user', content: 'ok decided, thanks, that fix works now' } },
  ].map((line) => JSON.stringify(line)).join('\n'))
  const past = new Date(Date.now() - 60 * 60 * 1000)
  fs.utimesSync(file, past, past)
}
const answer = { type: 'finding', title: 'Zyxwv quorble cache keeps raw fields', summary: 'The zyxwv quorble cache must store raw fields and sources or queries crash on stale entries.', tags: ['retrieval'], sources: ['https://docs.example.org/quorble-cache'], body: 'The zyxwv quorble cache must keep raw fields and sources because stale entries crash queries after an upgrade. Rebuild the cache when the format version changes. The rebuild runs on the next query and takes a few seconds on a large vault, so schedule it after upgrades.' }

try {
  fs.writeFileSync(gitconfig, '[user]\n\tname = nightly-test\n\temail = nightly@example.invalid\n[init]\n\tdefaultBranch = main\n')
  const init = spawnSync(process.execPath, [cliPath, 'init', vault], { encoding: 'utf8', env: { ...env, ALAMBIC_ROOT: '' } })
  assert.equal(init.status, 0, init.stderr)
  fs.writeFileSync(path.join(vault, 'kb/eval-anchor.md'), '---\ntype: reference\nstatus: verified\nsummary: "Anchor note for the nightly eval gate fixture"\nsources:\n  - "https://docs.example.org/eval-anchor"\ncreated: 2026-09-24\nupdated: 2026-09-24\ntags:\n  - retrieval\n---\n\n# Plumbus dinglebop fleeb\n\nThe plumbus dinglebop fleeb anchor answers the fixture eval queries.\n')
  fs.writeFileSync(path.join(vault, '_meta/evals/attention-compile.tsv'), `query\texpected\tkind\n${'plumbus dinglebop fleeb\tkb/eval-anchor.md\tlexical\n'.repeat(5)}`)
  fs.appendFileSync(path.join(vault, 'kb/_index.md'), '\n- [[eval-anchor]]\n')
  const runSh = path.join(vault, '_meta/tests/run.sh')
  fs.writeFileSync(runSh, `${fs.readFileSync(runSh, 'utf8').split('\n').filter((line) => !/ eval --suite /.test(line)).join('\n')}\n"$ROOT/_meta/alambic" eval --suite attention-compile\n`)
  git(['init', '-q', '-b', 'main'])
  git(['add', '-A'])
  git(['commit', '-q', '-m', 'init'])
  fs.mkdirSync(path.join(vault, 'node_modules'))
  for (const name of fs.readdirSync(path.join(root, 'node_modules'))) fs.symlinkSync(path.join(root, 'node_modules', name), path.join(vault, 'node_modules', name))
  git(['init', '-q', '--bare', remote], temp)
  git(['remote', 'add', 'origin', remote])
  git(['push', '-q', 'origin', 'main'])
  git(['remote', 'set-head', 'origin', 'main'])
  fs.writeFileSync(fake, `#!/bin/sh\ncat >/dev/null\nprintf '%s' '${JSON.stringify(answer)}'\n`, { mode: 0o755 })

  const dry = nightly(['--dry-run'])
  assert.equal(dry.ok, true, JSON.stringify(dry))
  assert.equal(dry.commit, null)
  let warm = nightly()
  for (let index = 0; index < 10 && warm.ok && warm.commit; index += 1) warm = nightly()
  assert.equal(warm.ok, true, JSON.stringify(warm))
  assert.equal(warm.commit, null, 'heals converge within ten runs')
  assert.equal(nightly().commit, null, 'a run with no input is idempotent')
  const base = remoteCount()

  writeSession('s1.jsonl', 'claude-s1')
  const first = nightly()
  assert.equal(first.ok, true, JSON.stringify(first))
  assert.equal(first.commit, null, 'a pending session note never commits')
  assert.equal(remoteCount(), base)
  const inboxDir = path.join(vault, 'docs/inbox/ai')
  const pending = fs.readdirSync(inboxDir).filter((name) => name.startsWith('harvest-'))
  assert.equal(pending.length, 1, JSON.stringify(first.steps))
  assert.equal(git(['status', '--porcelain']), '', 'harvest staging stays gitignored')
  const note = `docs/inbox/ai/${pending[0]}`

  const accepted = spawnSync('python3', ['-c', 'import pty, sys; sys.exit(pty.spawn(sys.argv[1:]) >> 8)', process.execPath, cliPath, 'review', '--inbox', note, '--decision', 'accept', '--reason', 'checked the cache rule'], { encoding: 'utf8', input: '', env })
  assert.equal(accepted.status, 0, accepted.stdout + accepted.stderr)

  const second = nightly()
  assert.equal(second.ok, true, JSON.stringify(second))
  assert.ok(second.commit, `accepted note is committed: ${JSON.stringify(second)}`)
  assert.equal(second.pushed, true)
  assert.ok(second.files.every((file) => file.startsWith('kb/')), second.files.join(','))
  assert.equal(remoteCount(), base + 1)
  assert.equal(git(['rev-parse', 'main'], remote), git(['rev-parse', 'HEAD']))
  assert.equal(git(['log', '-1', '--format=%s']), 'chore(sidekick): nightly heals')
  const promoted = second.files.find((file) => file !== 'kb/_index.md')
  assert.match(fs.readFileSync(path.join(vault, promoted), 'utf8'), /^reviewed_by: human:alambic-review$/m)
  assert.equal(fs.existsSync(path.join(vault, note)), false)

  const kbBefore = fs.readdirSync(path.join(vault, 'kb')).sort()
  writeSession('s2.jsonl', 'claude-s2')
  const replay = nightly()
  assert.equal(replay.ok, true, JSON.stringify(replay))
  assert.equal(replay.commit, null, 'a replayed session is a noop')
  assert.equal(remoteCount(), base + 1)
  assert.deepEqual(fs.readdirSync(path.join(vault, 'kb')).sort(), kbBefore)
  assert.ok(fs.readdirSync(path.join(inboxDir, 'processed')).some((name) => name.startsWith('noop-harvest-')))

  const promotedText = fs.readFileSync(path.join(vault, promoted), 'utf8')
  const update = { ...answer, body: 'The zyxwv quorble cache rebuild must hold the vault lock, otherwise two agents rebuilding at once interleave entries and the cache keeps a torn index until the next format bump. Take the lock before the rebuild and release it after the index is written back.' }
  fs.writeFileSync(fake, `#!/bin/sh\ncat >/dev/null\nprintf '%s' '${JSON.stringify(update)}'\n`, { mode: 0o755 })
  writeSession('s3.jsonl', 'claude-s3')
  assert.equal(nightly().commit, null, 'a pending update never commits')
  const updateDrafts = fs.readdirSync(inboxDir).filter((name) => name.startsWith('harvest-'))
  assert.equal(updateDrafts.length, 1, JSON.stringify(updateDrafts))
  const updateAccepted = spawnSync('python3', ['-c', 'import pty, sys; sys.exit(pty.spawn(sys.argv[1:]) >> 8)', process.execPath, cliPath, 'review', '--inbox', `docs/inbox/ai/${updateDrafts[0]}`, '--decision', 'accept', '--reason', 'checked the lock rule'], { encoding: 'utf8', input: '', env })
  assert.equal(updateAccepted.status, 0, updateAccepted.stdout + updateAccepted.stderr)
  const updated = nightly()
  assert.equal(updated.ok, true, JSON.stringify(updated))
  assert.ok(updated.commit, `accepted update is committed: ${JSON.stringify(updated)}`)
  assert.equal(updated.pushed, true)
  assert.ok(updated.files.includes(promoted), updated.files.join(','))
  assert.ok(updated.files.every((file) => file.startsWith('kb/')), updated.files.join(','))
  const updatedText = fs.readFileSync(path.join(vault, promoted), 'utf8')
  assert.ok(updatedText.startsWith(promotedText.slice(0, promotedText.indexOf('updated:'))), 'an update keeps the note head')
  assert.match(updatedText, /torn index until the next format bump/)
  assert.equal(remoteCount(), base + 2)
  writeSession('s4.jsonl', 'claude-s4')
  const updateReplay = nightly()
  assert.equal(updateReplay.ok, true, JSON.stringify(updateReplay))
  assert.equal(updateReplay.commit, null, 'a replayed update is a noop')
  assert.equal(remoteCount(), base + 2)
  assert.equal(fs.readFileSync(path.join(vault, promoted), 'utf8'), updatedText)
  assert.deepEqual(fs.readdirSync(inboxDir).filter((name) => name.startsWith('harvest-')), [], 'the replayed update is archived')

  fs.writeFileSync(path.join(vault, 'kb/broken-note.md'), 'no frontmatter\n')
  git(['add', 'kb/broken-note.md'])
  git(['commit', '-q', '-m', 'broken'])
  git(['push', '-q', 'origin', 'main'])
  const red = nightly()
  assert.equal(red.ok, false)
  assert.match(red.reason, /red gates: .*validate/)
  assert.equal(red.commit, null)
  assert.equal(remoteCount(), base + 3)
  git(['rm', '-q', 'kb/broken-note.md'])
  git(['commit', '-q', '-m', 'unbroken'])
  git(['push', '-q', 'origin', 'main'])
  const runner = path.join(vault, '_meta/tests/run.sh')
  const listed = fs.readFileSync(runner, 'utf8')
  assert.match(listed, /eval --suite /, 'the vault lists its eval suites')
  fs.writeFileSync(runner, `${listed}"$ROOT/_meta/alambic" eval --suite missing-suite\n`)
  git(['commit', '-q', '-am', 'missing suite'])
  git(['push', '-q', 'origin', 'main'])
  writeSession('s5.jsonl', 'claude-s5')
  const redEval = nightly()
  assert.equal(redEval.ok, false)
  assert.match(redEval.reason, /red gates: evals/, JSON.stringify(redEval))
  assert.match(redEval.steps.find((item) => item.name === 'evals').error, /missing-suite/)
  assert.equal(redEval.commit, null, 'a red eval blocks the commit')
  for (const [label, text, error] of [['dynamic suite', `${listed}"$ROOT/_meta/alambic" eval --suite "$SUITE"\n`, /unparsed eval suite/], ['chained suites', `${listed}"$ROOT/_meta/alambic" eval --suite missing-suite; "$ROOT/_meta/alambic" eval --suite attention-compile\n`, /missing-suite/], ['no suites', listed.split('\n').filter((line) => !/ eval --suite /.test(line)).join('\n'), /no eval suites/]]) {
    fs.writeFileSync(runner, text)
    git(['commit', '-q', '-am', label])
    git(['push', '-q', 'origin', 'main'])
    const blind = nightly()
    assert.match(blind.reason || '', /red gates: evals/, label)
    assert.match(blind.steps.find((item) => item.name === 'evals').error, error, label)
  }
  fs.writeFileSync(runner, listed.replace(/eval --suite ([\w-]+)/g, 'eval --suite "$1"'))
  git(['commit', '-q', '-am', 'quoted suites'])
  git(['push', '-q', 'origin', 'main'])
  const compileSet = path.join(vault, '_meta/evals/attention-compile.tsv')
  const compileText = fs.readFileSync(compileSet, 'utf8')
  fs.writeFileSync(compileSet, compileText.replace(/\tkb\/[^\t]+\.md\t/, '\tkb/vault-only-missing-note.md\t'))
  git(['commit', '-q', '-am', 'vault eval data'])
  git(['push', '-q', 'origin', 'main'])
  writeSession('s6.jsonl', 'claude-s6')
  const vaultEval = nightly()
  assert.match(vaultEval.reason || '', /red gates: evals/, 'the evals read the vault, not the engine')
  assert.match(vaultEval.steps.find((item) => item.name === 'evals').error, /attention-compile/)
  fs.writeFileSync(compileSet, compileText)
  git(['commit', '-q', '-am', 'engine eval data'])
  git(['push', '-q', 'origin', 'main'])

  fs.appendFileSync(path.join(vault, 'README.md'), '\nlocal edit\n')
  const dirty = nightly()
  assert.match(dirty.reason, /preflight: tracked tree or index is dirty/)
  git(['checkout', '--', 'README.md'])

  const readme = fs.readFileSync(path.join(vault, 'README.md'), 'utf8')
  fs.appendFileSync(path.join(vault, 'README.md'), '\nstaged edit\n')
  git(['add', 'README.md'])
  fs.writeFileSync(path.join(vault, 'README.md'), readme)
  assert.match(nightly().reason, /preflight: tracked tree or index is dirty/, 'an index-only change is dirty')
  git(['reset', '-q'])

  fs.writeFileSync(path.join(vault, 'kb/session.jsonl'), '{"role":"user"}\n')
  const untracked = nightly()
  assert.match(untracked.reason, /preflight: untracked files in publishable paths/)
  assert.deepEqual(untracked.preflight.paths, ['kb/session.jsonl'])
  fs.rmSync(path.join(vault, 'kb/session.jsonl'))

  git(['checkout', '-q', '-b', 'side'])
  assert.match(nightly().reason, /preflight: not on the default branch/)
  assert.match(nightly([]).reason, /preflight: not on the default branch/, 'a local commit run checks the branch too')
  assert.equal(nightly(['--dry-run']).ok, true, 'a dry run works on any branch')
  git(['checkout', '-q', 'main'])

  const { exportTree, nightlyCommit, nightlyPreflight, publishableTree, resetToUpstream } = await import(path.join(root, '_meta/lib/nightly.mjs'))
  const { displacedEdits, writeChecked } = await import(path.join(root, '_meta/lib/write-journal.mjs'))
  const preflight = nightlyPreflight(vault, { push: true, env })
  assert.equal(preflight.ok, true, JSON.stringify(preflight))
  fs.writeFileSync(path.join(vault, 'kb/extra-note.md'), fs.readFileSync(path.join(vault, promoted), 'utf8').replace(/^# .*$/m, '# Extra note'))
  fs.appendFileSync(path.join(vault, 'package.json'), '\n')
  const refused = nightlyCommit(vault, { push: true, preflight, env })
  assert.equal(refused.ok, false)
  assert.match(refused.reason, /outside the commit allowlist/)
  assert.deepEqual(refused.paths, ['package.json'])
  assert.equal(git(['diff', '--cached', '--name-only']), '', 'refused commit leaves nothing staged')
  git(['checkout', '--', 'package.json'])
  fs.rmSync(path.join(vault, 'kb/extra-note.md'))

  fs.writeFileSync(path.join(vault, 'kb/extra-note.md'), fs.readFileSync(path.join(vault, promoted), 'utf8').replace(/^# .*$/m, '# Extra note'))
  const snapshot = publishableTree(vault, env)
  assert.equal(snapshot.ok, true, JSON.stringify(snapshot))
  assert.equal(git(['diff', '--cached', '--name-only']), '', 'the snapshot leaves nothing staged')
  fs.appendFileSync(path.join(vault, 'kb/extra-note.md'), '\nEdited after the gates ran.\n')
  const raced = nightlyCommit(vault, { push: true, preflight, env, expectedTree: snapshot.tree })
  assert.equal(raced.ok, false)
  assert.match(raced.reason, /changed after the gates/)
  assert.equal(git(['diff', '--cached', '--name-only']), '', 'a raced commit leaves nothing staged')
  fs.rmSync(path.join(vault, 'kb/extra-note.md'))

  const journal = path.join(temp, 'writes.jsonl')
  const ownText = fs.readFileSync(path.join(vault, promoted), 'utf8').replace(/^# .*$/m, '# Own note')
  fs.writeFileSync(path.join(vault, 'kb/own-note.md'), ownText)
  fs.writeFileSync(journal, `${JSON.stringify({ path: path.resolve(vault, 'kb/own-note.md'), before: null, after: crypto.createHash('sha256').update(ownText).digest('hex') })}\n`)
  fs.writeFileSync(path.join(vault, 'kb/human-note.md'), ownText.replace('# Own note', '# Human note'))
  const foreign = nightlyCommit(vault, { push: true, preflight, env, journal })
  assert.equal(foreign.ok, false)
  assert.match(foreign.reason, /not written by this run/)
  assert.deepEqual(foreign.paths, ['kb/human-note.md'], 'a human edit made during the run is never published')
  fs.rmSync(path.join(vault, 'kb/human-note.md'))
  fs.appendFileSync(path.join(vault, 'kb/own-note.md'), '\nHuman touch after the run wrote it.\n')
  assert.deepEqual(nightlyCommit(vault, { push: true, preflight, env, journal }).paths, ['kb/own-note.md'], 'an edit on top of a run write is refused')
  fs.rmSync(path.join(vault, 'kb/own-note.md'))

  const displacedDir = path.join(vault, '.git/swap-displaced')
  const swapEnv = { ALAMBIC_WRITE_JOURNAL: path.join(temp, 'swap.jsonl'), ALAMBIC_DISPLACED_DIR: displacedDir }
  const swapped = path.join(vault, promoted)
  const swapHead = fs.readFileSync(swapped, 'utf8')
  fs.writeFileSync(swapped, `${swapHead}\nHuman edit.\n`)
  assert.equal(writeChecked(swapped, swapHead, `${swapHead}\nStep.\n`, swapEnv), false)
  assert.equal(fs.readFileSync(swapped, 'utf8'), `${swapHead}\nHuman edit.\n`, 'a refused swap keeps the human edit in place')
  assert.deepEqual(displacedEdits(displacedDir), [], 'a refused swap leaves no displaced copy')
  fs.writeFileSync(swapped, swapHead)
  assert.equal(writeChecked(swapped, swapHead, `${swapHead}\nStep.\n`, swapEnv), true)
  const [copy] = fs.readdirSync(displacedDir)
  assert.deepEqual(displacedEdits(displacedDir), [], 'an intact displaced copy never blocks')
  fs.appendFileSync(path.join(displacedDir, copy), 'Late human write into the old inode.\n')
  assert.deepEqual(displacedEdits(displacedDir).map((file) => path.basename(file)), [copy], 'a late write into the displaced file is preserved')
  assert.throws(() => displacedEdits(path.join(displacedDir, copy)), /ENOTDIR/, 'an unreadable displaced directory blocks instead of looking empty')
  assert.match(nightlyCommit(vault, { push: false, preflight, env: { ...env, ALAMBIC_DISPLACED_DIR: displacedDir } }).reason, /concurrent edits were preserved/)
  fs.rmSync(displacedDir, { recursive: true })
  fs.writeFileSync(swapped, swapHead)
  const displacedCount = () => fs.readdirSync(path.join(vault, '.git/alambic-displaced')).length
  assert.ok(displacedCount() > 0, 'nightly keeps the old inodes it replaced or archived')
  const beforeDirect = displacedCount()
  assert.equal(writeChecked(swapped, swapHead, `${swapHead}\nDirect step.\n`, {}), true)
  assert.equal(displacedCount(), beforeDirect + 1, 'a write outside nightly displaces the old file too')
  fs.writeFileSync(swapped, swapHead)
  fs.rmSync(path.join(vault, '.git/alambic-displaced'), { recursive: true })
  const gitDisplaced = path.join(vault, '.git/alambic-displaced')
  fs.mkdirSync(gitDisplaced, { recursive: true })
  fs.writeFileSync(path.join(gitDisplaced, `${'0'.repeat(64)}-kept-note.md`), 'Kept human edit.\n')
  assert.match(nightly(['--dry-run']).reason, /concurrent edits preserved/, 'a preserved edit blocks the next run until a human resolves it')
  fs.rmSync(gitDisplaced, { recursive: true })
  const patternRun = (value) => {
    const result = spawnSync(process.execPath, [cliPath, 'nightly', '--dry-run', '--json'], { cwd: temp, encoding: 'utf8', env: { ...env, ALAMBIC_LEAK_PATTERNS_FILE: value }, timeout: 300_000 })
    return JSON.parse(result.stdout)
  }
  const leakScan = (file) => spawnSync('/bin/bash', [path.join(root, '_meta/tests/leak-scan.sh'), vault], { encoding: 'utf8', env: { ...env, ALAMBIC_LEAK_PATTERNS_FILE: file } })
  assert.notEqual(leakScan(path.join(temp, 'gone-patterns')).status, 0, 'the scanner refuses a configured pattern file that vanished')
  assert.notEqual(leakScan(temp).status, 0, 'the scanner refuses a pattern path that is not a file')
  const nulRepo = path.join(temp, 'nul-repo')
  const nulMarker = ['qx7', 'nul', 'mark'].join('-')
  fs.mkdirSync(nulRepo)
  git(['init', '-q'], nulRepo)
  fs.writeFileSync(path.join(nulRepo, 'note.md'), `binary\u0000 ${nulMarker}\n`)
  fs.writeFileSync(path.join(temp, 'nul-patterns'), `${nulMarker}\n`)
  const nulScan = spawnSync('/bin/bash', [path.join(root, '_meta/tests/leak-scan.sh'), nulRepo], { encoding: 'utf8', env: { ...env, ALAMBIC_LEAK_PATTERNS_FILE: path.join(temp, 'nul-patterns') } })
  assert.notEqual(nulScan.status, 0, 'a private marker behind a NUL byte is still caught')
  assert.match(nulScan.stderr, /note\.md:1/, 'the hit names the file')
  assert.equal(nulScan.stderr.includes(nulMarker), false, 'a single-file hit never prints the marker')
  fs.rmSync(nulRepo, { recursive: true })
  fs.rmSync(path.join(temp, 'nul-patterns'))
  assert.match(patternRun('missing-patterns').reason, /configured or present but is not a readable file/, 'a configured but missing pattern file refuses the run')
  fs.mkdirSync(path.join(vault, '.leak-patterns'))
  assert.match(nightly(['--dry-run']).reason, /configured or present but is not a readable file/, 'a default pattern path that is not a file refuses the run')
  fs.rmSync(path.join(vault, '.leak-patterns'), { recursive: true })
  fs.symlinkSync(path.join(temp, 'nowhere-patterns'), path.join(vault, '.leak-patterns'))
  const { ALAMBIC_LEAK_PATTERNS_FILE: _configured, ...bareEnv } = env
  assert.notEqual(spawnSync('/bin/bash', [path.join(root, '_meta/tests/leak-scan.sh'), vault], { encoding: 'utf8', env: bareEnv }).status, 0, 'the scanner refuses a dangling default pattern link')
  assert.match(nightly(['--dry-run']).reason, /configured or present but is not a readable file/, 'a dangling default pattern link refuses the run')
  fs.unlinkSync(path.join(vault, '.leak-patterns'))
  fs.writeFileSync(path.join(vault, '.git/private-patterns'), 'zyxwv quorble\n')
  const relativePatterns = patternRun('.git/private-patterns')
  assert.match(relativePatterns.reason || '', /red gates: .*leak-scan/, 'a relative pattern file resolves against the vault')
  fs.rmSync(path.join(vault, '.git/private-patterns'))

  const tracked = path.join(vault, promoted)
  const headText = fs.readFileSync(tracked, 'utf8')
  const humanText = `${headText}\nHuman edit before the step read the note.\n`
  fs.writeFileSync(tracked, humanText)
  fs.writeFileSync(journal, '')
  assert.equal(writeChecked(tracked, headText, `${humanText}\nStep write.\n`, { ALAMBIC_WRITE_JOURNAL: journal }), false, 'a checked write refuses a file that changed since its read')
  assert.equal(writeChecked(tracked, humanText, `${humanText}\nStep write.\n`, { ALAMBIC_WRITE_JOURNAL: journal }), true)
  const inherited = nightlyCommit(vault, { push: true, preflight, env, journal })
  assert.match(inherited.reason || '', /not written by this run/)
  assert.deepEqual(inherited.paths, [promoted], 'a step write built on a human edit is never published')
  fs.writeFileSync(tracked, headText)
  fs.writeFileSync(journal, '')
  assert.equal(writeChecked(tracked, headText, `${headText}\nStep write.\n`, { ALAMBIC_WRITE_JOURNAL: journal }), true)
  const indexLock = path.join(vault, '.git/index.lock')
  fs.writeFileSync(indexLock, '')
  assert.match(nightlyCommit(vault, { push: false, preflight, env, journal }).reason, /index is locked/, 'finalization waits for no one and refuses a held index lock')
  fs.rmSync(indexLock)
  const mainBefore = git(['rev-parse', 'main'])
  git(['checkout', '-q', '-b', 'feature'])
  assert.match(nightlyCommit(vault, { push: false, preflight, env, journal }).reason, /branch changed during the run/, 'a branch switch after preflight never takes the commit')
  assert.equal(git(['rev-parse', 'feature']), mainBefore)
  git(['checkout', '-q', 'main'])
  git(['branch', '-q', '-D', 'feature'])
  const { writeSync } = fs
  fs.writeSync = (fd, buffer, offset = 0, length = buffer.length - offset, ...rest) => writeSync(fd, buffer, offset, Math.min(length, 64), ...rest)
  let ownCommit
  try { ownCommit = nightlyCommit(vault, { push: false, preflight, env, journal }) } finally { fs.writeSync = writeSync }
  assert.equal(ownCommit.ok, true, JSON.stringify(ownCommit))
  assert.equal(spawnSync('git', ['-C', vault, 'ls-files', '--error-unmatch', promoted]).status, 0, 'a short write never publishes a truncated index')
  assert.equal(git(['status', '--porcelain']), '', 'the real index follows the new commit')
  assert.equal(fs.existsSync(indexLock), false)
  git(['reset', '-q', '--hard', 'HEAD^'])
  const resumeHead = git(['rev-parse', 'HEAD'])
  git(['checkout', '-q', '-b', 'resume-side'])
  assert.match(resetToUpstream(vault, env, resumeHead, resumeHead, 'main').reason, /branch changed during preflight/, 'a resume never resets a branch preflight did not validate')
  git(['checkout', '-q', 'main'])
  git(['branch', '-q', '-D', 'resume-side'])
  fs.mkdirSync(path.join(vault, '.git/info'), { recursive: true })
  fs.writeFileSync(path.join(vault, '.git/info/attributes'), '*.md filter=mask\n')
  git(['config', 'filter.mask.smudge', 'tr e E'])
  git(['config', 'filter.mask.clean', 'cat'])
  const exported = path.join(temp, 'exported')
  fs.mkdirSync(exported)
  try { assert.equal(exportTree(vault, env, git(['rev-parse', 'HEAD^{tree}']), exported), true) } finally {
    fs.rmSync(path.join(vault, '.git/info/attributes'))
    git(['config', '--remove-section', 'filter.mask'])
  }
  const blob = spawnSync('git', ['cat-file', 'blob', `HEAD:${promoted}`], { cwd: vault, env }).stdout
  assert.ok(fs.readFileSync(path.join(exported, promoted)).equals(blob), 'the gates read the committed blob, never a smudged checkout')
  fs.rmSync(exported, { recursive: true })

  fs.appendFileSync(path.join(vault, 'package.json'), '\n')
  git(['add', 'package.json'])
  const staged = nightlyCommit(vault, { push: true, preflight, env })
  assert.match(staged.reason, /index changed during the run/)
  assert.equal(git(['diff', '--cached', '--name-only']), 'package.json', 'a refused run keeps what the user staged')
  git(['reset', '-q', '--', 'package.json'])
  git(['checkout', '--', 'package.json'])

  fs.mkdirSync(path.join(vault, 'kb/imports'))
  fs.writeFileSync(path.join(vault, 'kb/imports/draft.md'), ownText)
  const nested = nightlyCommit(vault, { push: true, preflight, env })
  assert.match(nested.reason, /outside the commit allowlist/)
  assert.deepEqual(nested.paths, ['kb/imports/draft.md'], 'nested kb paths the validator skips are never published')
  fs.rmSync(path.join(vault, 'kb/imports'), { recursive: true })

  const stuckNote = path.join(vault, 'kb', path.basename(promoted))
  fs.appendFileSync(stuckNote, '\nLocal nightly commit that never reached the remote.\n')
  const addedNote = path.join(vault, 'kb/resumed-new-note.md')
  fs.writeFileSync(addedNote, fs.readFileSync(stuckNote, 'utf8').replace(/^# .*$/m, '# Resumed new note'))
  fs.appendFileSync(path.join(vault, 'kb/_index.md'), '\n- [[resumed-new-note]] - resumed by nightly\n')
  git(['add', 'kb'])
  git(['commit', '-q', '-m', 'chore(sidekick): nightly heals'])
  assert.match(nightly().reason, /HEAD differs from origin/, 'a commit nightly did not record is not resumed, even under its subject')
  git(['reset', '-q', 'HEAD^'])
  assert.equal(nightlyCommit(vault, { push: false, preflight, env }).ok, true, 'nightly records its own unpushed commit')
  const before = remoteCount()
  const pendingHead = git(['rev-parse', 'HEAD'])
  fs.writeFileSync(indexLock, '')
  assert.match(nightly().reason, /index is locked/, 'resume never resets an index someone else holds')
  assert.equal(git(['rev-parse', 'HEAD']), pendingHead)
  fs.rmSync(indexLock)
  const resumed = nightly()
  assert.equal(resumed.ok, true, JSON.stringify(resumed))
  assert.ok(resumed.preflight.resumed, 'an unpushed nightly commit is resumed')
  assert.equal(resumed.pushed, true)
  assert.equal(remoteCount(), before + 1)
  assert.ok(resumed.files.includes('kb/resumed-new-note.md'), 'a note added by the resumed commit is published')
  git(['commit', '-q', '--allow-empty', '-m', 'someone else'])
  assert.match(nightly().reason, /HEAD differs from origin/, 'a foreign local commit is not resumed')
  git(['reset', '-q', '--hard', 'HEAD^'])

  const inVault = nightly(['--push'])
  assert.equal(inVault.ok, true)
  const insideEnv = spawnSync(process.execPath, [cliPath, 'nightly', '--dry-run', '--json'], { cwd: vault, encoding: 'utf8', env: { ...env, ALAMBIC_STATE_DIR: path.join(vault, 'kb/state') } })
  assert.match(JSON.parse(insideEnv.stdout).reason, /state dir is inside the vault/)

  fs.mkdirSync(path.join(state, 'harvest/lock'), { recursive: true })
  const locked = nightly()
  assert.equal(locked.locked, true)
  fs.rmSync(path.join(state, 'harvest/lock'), { recursive: true })
  console.log('nightly: ok')
} finally {
  fs.rmSync(temp, { recursive: true, force: true })
}
